ALTER TABLE topicos
DROP COLUMN dataCriacao,
DROP COLUMN dataAlteracao,
ADD COLUMN dataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN dataAlteracao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;