-- MySQL Script generated by MySQL Workbench
-- Wed Nov 24 18:50:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Projetos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Projetos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Projetos` (
  `idProjetos` INT NOT NULL AUTO_INCREMENT,
  `nomeProjeto` VARCHAR(45) NOT NULL,
  `codigoCriador` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(300) NULL,
  PRIMARY KEY (`idProjetos`),
  UNIQUE INDEX `idProjetos_UNIQUE` (`idProjetos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(60) NOT NULL,
  `dataNascimento` DATE NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `cancelado` TINYINT NULL,
  `dataAlteracao` DATETIME NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cargos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cargos` (
  `idCargos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `cancelado` TINYINT NULL,
  `Cargoscol` VARCHAR(45) NULL,
  `dataAlteracao` DATETIME NULL,
  `usuarioAlterou` INT NULL,
  PRIMARY KEY (`idCargos`),
  INDEX `usuarioAlterou_idx` (`usuarioAlterou` ASC) VISIBLE,
  CONSTRAINT `usuarioAlterou_c`
    FOREIGN KEY (`usuarioAlterou`)
    REFERENCES `mydb`.`ProjetoColaboradores` (`idProjetoColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjetoColaboradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProjetoColaboradores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProjetoColaboradores` (
  `idProjetoColaborador` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idProjeto` INT NOT NULL,
  `dataAdmissao` DATETIME NULL,
  `cancelado` INT NULL,
  `idCargo` INT NOT NULL,
  PRIMARY KEY (`idProjetoColaborador`),
  INDEX `codigoUsuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `idProjeto_idx` (`idProjeto` ASC) VISIBLE,
  INDEX `idCargo_idx` (`idCargo` ASC) VISIBLE,
  CONSTRAINT `codigoUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProjeto`
    FOREIGN KEY (`idProjeto`)
    REFERENCES `mydb`.`Projetos` (`idProjetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCargo`
    FOREIGN KEY (`idCargo`)
    REFERENCES `mydb`.`Cargos` (`idCargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Permissoes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Permissoes` (
  `idPermissoes` INT NOT NULL AUTO_INCREMENT,
  `idColaborador` INT NOT NULL,
  `idCargo` INT NULL,
  `dataAlteracao` DATETIME NULL,
  `usuarioAlterou` INT NULL,
  PRIMARY KEY (`idPermissoes`),
  INDEX `idProjetoColaboradores_idx` (`idColaborador` ASC) INVISIBLE,
  INDEX `idCargo_idx` (`idCargo` ASC) VISIBLE,
  INDEX `usuarioAlterou_idx` (`usuarioAlterou` ASC) VISIBLE,
  CONSTRAINT `idProjetoColaborador`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `mydb`.`ProjetoColaboradores` (`idProjetoColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCargo_p`
    FOREIGN KEY (`idCargo`)
    REFERENCES `mydb`.`Cargos` (`idCargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarioAlterou_p`
    FOREIGN KEY (`usuarioAlterou`)
    REFERENCES `mydb`.`ProjetoColaboradores` (`idProjetoColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `idStatus` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cancelado` TINYINT NULL,
  `Statuscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sprints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sprints` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sprints` (
  `idSprints` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataFinal` DATETIME NULL,
  `cancelada` TINYINT NULL,
  `Sprintscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idSprints`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarefas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tarefas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tarefas` (
  `idTarefas` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(45) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `prioridade` INT NOT NULL,
  `cancelada` TINYINT NULL,
  `ultimaResposta` DATETIME NULL,
  `idAutor` INT NOT NULL,
  `autorRazaoSocial` VARCHAR(45) NOT NULL,
  `idProjeto` INT NOT NULL,
  `idStatus` INT NOT NULL,
  `idSprint` INT NULL,
  PRIMARY KEY (`idTarefas`),
  INDEX `idAutor_idx` (`idAutor` ASC) VISIBLE,
  INDEX `idProjeto_idx` (`idProjeto` ASC) VISIBLE,
  INDEX `idStatus_idx` (`idStatus` ASC) VISIBLE,
  INDEX `idSprint_idx` (`idSprint` ASC) VISIBLE,
  CONSTRAINT `idAutor`
    FOREIGN KEY (`idAutor`)
    REFERENCES `mydb`.`ProjetoColaboradores` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProjeto_t`
    FOREIGN KEY (`idProjeto`)
    REFERENCES `mydb`.`Projetos` (`idProjetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idStatus`
    FOREIGN KEY (`idStatus`)
    REFERENCES `mydb`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSprint`
    FOREIGN KEY (`idSprint`)
    REFERENCES `mydb`.`Sprints` (`idSprints`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TarefasTempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TarefasTempo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TarefasTempo` (
  `idTarefasTempo` INT NOT NULL AUTO_INCREMENT,
  `idTarefa` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  `idStatus` INT NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataFinal` DATETIME NULL,
  PRIMARY KEY (`idTarefasTempo`),
  INDEX `idTarefa_idx` (`idTarefa` ASC) VISIBLE,
  INDEX `idColaborador_idx` (`idColaborador` ASC) VISIBLE,
  INDEX `idStatus_idx` (`idStatus` ASC) VISIBLE,
  CONSTRAINT `idTarefa_t`
    FOREIGN KEY (`idTarefa`)
    REFERENCES `mydb`.`Tarefas` (`idTarefas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idColaborador`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `mydb`.`ProjetoColaboradores` (`idProjetoColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idStatus_t`
    FOREIGN KEY (`idStatus`)
    REFERENCES `mydb`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TarefasRespostas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TarefasRespostas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TarefasRespostas` (
  `idTarefasResposta` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idTarefa` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  `statusAnterior` INT NOT NULL,
  `statusNovo` INT NOT NULL,
  `resposta` VARCHAR(45) NOT NULL,
  `dataResposta` DATETIME NOT NULL,
  PRIMARY KEY (`idTarefasResposta`),
  INDEX `idTarefa_idx` (`idTarefa` ASC) VISIBLE,
  INDEX `idColaborador_idx` (`idColaborador` ASC) VISIBLE,
  CONSTRAINT `idTarefa_tt`
    FOREIGN KEY (`idTarefa`)
    REFERENCES `mydb`.`Tarefas` (`idTarefas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idColaborador_tt`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `mydb`.`ProjetoColaboradores` (`idProjetoColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Topicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Topicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Topicos` (
  `idTopicos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(70) NULL,
  `cancelado` TINYINT NULL,
  `idCriador` INT NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  PRIMARY KEY (`idTopicos`),
  INDEX `idCriador_idx` (`idCriador` ASC) VISIBLE,
  CONSTRAINT `idCriador`
    FOREIGN KEY (`idCriador`)
    REFERENCES `mydb`.`ProjetoColaboradores` (`idProjetoColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Posts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Posts` (
  `idPosts` INT NOT NULL AUTO_INCREMENT,
  `idTopico` INT NOT NULL,
  `idAutor` INT NOT NULL,
  `idProjeto` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `cancelado` TINYINT NULL,
  `resposta` INT NULL,
  PRIMARY KEY (`idPosts`),
  INDEX `idAutor_idx` (`idAutor` ASC) VISIBLE,
  INDEX `idProjeto_idx` (`idProjeto` ASC) VISIBLE,
  INDEX `idTopico_idx` (`idTopico` ASC) VISIBLE,
  CONSTRAINT `idAutor_p`
    FOREIGN KEY (`idAutor`)
    REFERENCES `mydb`.`ProjetoColaboradores` (`idProjetoColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProjeto_p`
    FOREIGN KEY (`idProjeto`)
    REFERENCES `mydb`.`Projetos` (`idProjetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTopico`
    FOREIGN KEY (`idTopico`)
    REFERENCES `mydb`.`Topicos` (`idTopicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conversas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Conversas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Conversas` (
  `idConversa` INT NOT NULL,
  `idMensagemFixada` VARCHAR(45) NULL,
  `mensagemFixada` INT NULL,
  `grupo` INT NULL,
  `descricao` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NOT NULL,
  `perfil` LONGBLOB NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataAlteracao` DATETIME NULL,
  `usuarioAlterou` INT NULL,
  `cancelado` INT NULL,
  PRIMARY KEY (`idConversa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mensagens` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mensagens` (
  `idMensagem` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idConversa` INT NOT NULL,
  `horarioEnvio` DATETIME NOT NULL,
  `texto` TEXT NULL,
  PRIMARY KEY (`idMensagem`),
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `idConversa_idx` (`idConversa` ASC) VISIBLE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idConversa`
    FOREIGN KEY (`idConversa`)
    REFERENCES `mydb`.`Conversas` (`idConversa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reacoes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reacoes` (
  `idReacoes` INT NOT NULL AUTO_INCREMENT,
  `idMensagem` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `reacao` INT NULL,
  `cancelado` INT NULL,
  PRIMARY KEY (`idReacoes`),
  INDEX `idMensagem_idx` (`idMensagem` ASC) VISIBLE,
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idMensagem`
    FOREIGN KEY (`idMensagem`)
    REFERENCES `mydb`.`Mensagens` (`idMensagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuario_r`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ConversasFixadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ConversasFixadas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ConversasFixadas` (
  `idMensagensFixadas` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idConversa` INT NOT NULL,
  `cancelada` INT NULL,
  PRIMARY KEY (`idMensagensFixadas`),
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `idConversa_idx` (`idConversa` ASC) VISIBLE,
  CONSTRAINT `idUsuario_cf`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idConversa_cf`
    FOREIGN KEY (`idConversa`)
    REFERENCES `mydb`.`Conversas` (`idConversa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Participantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Participantes` (
  `idParticipantes` INT NOT NULL AUTO_INCREMENT,
  `idConversa` INT NOT NULL,
  `idParticipante` INT NOT NULL,
  `cancelado` INT NULL,
  PRIMARY KEY (`idParticipantes`),
  INDEX `idConversa_idx` (`idConversa` ASC) VISIBLE,
  INDEX `idParticipante_idx` (`idParticipante` ASC) VISIBLE,
  CONSTRAINT `idConversa_p`
    FOREIGN KEY (`idConversa`)
    REFERENCES `mydb`.`Conversas` (`idConversa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idParticipante`
    FOREIGN KEY (`idParticipante`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
